### PR TITLE
Linux Build Support

### PR DESCRIPTION
**Pull request by barishcb**
* Added Linux build support for Maya and python
* Added new Makefile for CMake command wrappers
* Fixing FindMaya.cmake to support Linux
* Typo inside simplex.h include
* Remove the namespaces from declarations
* Added typedef for UINT in simplex_maya node

### CODE REVIEW

**Comment by tbttfox** [comment]
Hey, thanks for tackling this.  Seriously, this has been on my to-do list for quite a while.
If you have any questions please feel free to ask.

**Comment by barishcb** [comment]
One of my friends (Rigging TD) requested for this. So the current solution is tested only with Maya 2019 and 2020 and Python(2.7). But not tested with Maya 2018 or below.  Also not tested with XSI. There is a small change in SimplexUI too.

I will update the README once you are happy with the change.

**Comment by tbttfox** [comment]
I can confirm build and functionality on Windows for Maya 2019 and 2020, and python 2.7
One of these days I'll set up CI, but for now, that's me!

So yeah, LGTM. Update the README and I'll merge

Also just FYI, XSI is only around for legacy reasons, so don't worry about it.

**Comment by barishcb** [comment]
Updated README with Linux build information

**Pull request merged**
